bpf: Only build bpf_do_trace_printk() with CONFIG_TRACE_PRINTK
bpf_do_trace_printk() and its lock are only used when TRACE_PRINTK is
enabled. With BPF_EVENTS on and TRACE_PRINTK off this fails to build:

  kernel/trace/bpf_trace.c:401:27: error: unused function
  'bpf_do_trace_printk' [-Werror,-Wunused-function]